package de.ngloader.core.inventory;

import org.bukkit.Material;

import de.ngloader.core.util.ItemFactory;

public class InventoryItem {

	public static final ItemFactory DEFAULT_BACKGROUND = new ItemFactory(Material.GRAY_STAINED_GLASS_PANE, " ").addAllFlag();
	public static final ItemFactory DEFAULT_SLOT_HOLDER = new ItemFactory(Material.RED_STAINED_GLASS_PANE, " ").addAllFlag();

	public static final ItemFactory DEFAULT_ARROW_RIGHT = new ItemFactory(Material.PLAYER_HEAD).setDisplayName("§aSeite §7%p").addAllFlag().setSkullProfile("ewogICJ0aW1lc3RhbXAiIDogMTYwMDk5NjI2NTkwOCwKICAicHJvZmlsZUlkIiA6ICJhNjhmMGI2NDhkMTQ0MDAwYTk1ZjRiOWJhMTRmOGRmOSIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfQXJyb3dMZWZ0IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Y3YWFjYWQxOTNlMjIyNjk3MWVkOTUzMDJkYmE0MzM0MzhiZTQ2NDRmYmFiNWViZjgxODA1NDA2MTY2N2ZiZTIiCiAgICB9CiAgfQp9");
	public static final ItemFactory DEFAULT_ARROW_LEFT = new ItemFactory(Material.PLAYER_HEAD).setDisplayName("§aSeite §7%p").addAllFlag().setSkullProfile("ewogICJ0aW1lc3RhbXAiIDogMTYwMDk5NjIzOTczOCwKICAicHJvZmlsZUlkIiA6ICJmZWYwMzllZmU2Y2Q0OTg3OWM4NDI2YTNlNjEzNDI3NyIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfQXJyb3dVcCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hMTU2YjMxY2JmOGY3NzQ1NDdkYzNmOTcxM2E3NzBlY2M1YzcyN2Q5NjdjYjAwOTNmMjY1NDZiOTIwNDU3Mzg3IgogICAgfQogIH0KfQ==");
	public static final ItemFactory DEFAULT_ARROW_UP = new ItemFactory(Material.PLAYER_HEAD).setDisplayName("§aSeite §7%p").addAllFlag().setSkullProfile("ewogICJ0aW1lc3RhbXAiIDogMTYwMDk5NjI3NjA3OSwKICAicHJvZmlsZUlkIiA6ICI1MGM4NTEwYjVlYTA0ZDYwYmU5YTdkNTQyZDZjZDE1NiIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfQXJyb3dSaWdodCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMzRlZjA2Mzg1MzcyMjJiMjBmNDgwNjk0ZGFkYzBmODVmYmUwNzU5ZDU4MWFhN2ZjZGYyZTQzMTM5Mzc3MTU4IgogICAgfQogIH0KfQ==");
	public static final ItemFactory DEFAULT_ARROW_DOWN = new ItemFactory(Material.PLAYER_HEAD).setDisplayName("§aSeite §7%p").addAllFlag().setSkullProfile("ewogICJ0aW1lc3RhbXAiIDogMTYwMDk5NjI1NDg4MiwKICAicHJvZmlsZUlkIiA6ICI2OGY1OWI5YjViMGI0YjA1YTlmMmUxZDE0MDVhYTM0OCIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfQXJyb3dEb3duIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZlM2Q3NTVjZWNiYjEzYTM5ZThlOTM1NDgyM2E5YTAyYTAxZGNlMGFjYTY4ZmZkNDJlM2VhOWE5ZDI5ZTJkZjIiCiAgICB9CiAgfQp9");
}